name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libreadline-dev libsodium-dev

      - name: Build
        run: make

      - name: Check binary exists
        run: test -f nosh

      - name: Test version command
        run: |
          ./nosh --version || true

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure Homebrew is installed
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";
          fi

      - name: Install dependencies
        run: |
          brew install gcc readline libsodium

      - name: Set Sodium environment variables
        run: |
          echo 'LDFLAGS="-L/usr/local/opt/libsodium/lib"' >> $GITHUB_ENV
          echo 'CPPFLAGS="-I/usr/local/opt/libsodium/include"' >> $GITHUB_ENV
          echo 'PKG_CONFIG_PATH="/usr/local/opt/libsodium/lib/pkgconfig"' >> $GITHUB_ENV

      - name: Build
        run: make
        env:
          LDFLAGS: ${{ env.LDFLAGS }}
          CPPFLAGS: ${{ env.CPPFLAGS }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}

      - name: Check binary exists
        run: test -f nosh

      - name: Test version command
        run: |
          ./nosh --version || true

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure Chocolatey is installed
        run: |
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force;
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
          }

      - name: Install dependencies
        run: |
          choco install -y mingw make

      - name: Download and extract libsodium
        run: |
          curl -L -o libsodium.zip https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip
          powershell -Command "Expand-Archive libsodium.zip -DestinationPath ."
          $staticDir = Get-ChildItem -Recurse -Directory -Filter "static" | Select-Object -First 1
          if ($staticDir) {
            Move-Item $staticDir.FullName libsodium
          } else {
            Write-Error "Expected directory structure not found."
          }

      - name: Set Sodium environment variables
        run: |
          $env:Path += ";$PWD\libsodium\bin"
          $env:INCLUDE = "$PWD\libsodium\include"
          $env:LIB = "$PWD\libsodium\lib"
          echo "INCLUDE=$env:INCLUDE" >> $GITHUB_ENV
          echo "LIB=$env:LIB" >> $GITHUB_ENV

      - name: Build
        run: make
        env:
          INCLUDE: ${{ env.INCLUDE }}
          LIB: ${{ env.LIB }}

      - name: Check binary exists
        run: if exist nosh.exe (echo Binary exists) else (exit 1)

      - name: Test version command
        run: .\nosh.exe --version || true