name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for git
        run: |
          if ! command -v git &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y git
          fi
          
      - id: get_version
        name: Get version
        run: |
          VERSION="0.1.0"
          COMMIT=$(git rev-parse --short HEAD || echo "unknown")
          VERSION_STRING="$VERSION-$COMMIT"
          echo "version=$VERSION_STRING" >> $GITHUB_OUTPUT

  build-linux:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config \
            libreadline-dev libmbedtls-dev libargon2-dev

      - name: Configure CMake
        run: |
          cmake -B build -S . \
          -DVERSION=${{needs.version.outputs.version}}

      - name: Build
        run: cmake --build build

      - name: Check binary
        run: test -f build/nosh

      - name: Test version
        run: ./build/nosh --version || true

      - uses: actions/upload-artifact@v4
        with:
          name: nosh-linux
          path: |
            build/nosh*
            build/*.so

  build-macos:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up OSXCross
        run: |
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross
          wget -nc https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          mv MacOSX11.3.sdk.tar.xz tarballs/
          UNATTENDED=1 ./build.sh
          echo "OSXCROSS_ROOT=$PWD" >> $GITHUB_ENV
          echo "$PWD/target/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang llvm

      - name: Configure CMake
        run: |
          cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=cmake/darwin-toolchain.cmake \
          -DCMAKE_SYSTEM_NAME=Darwin \
          -DCMAKE_OSX_ARCHITECTURES=x86_64 \
          -DCMAKE_C_COMPILER=o64-clang \
          -DCMAKE_CXX_COMPILER=o64-clang++ \
          -DVERSION=${{needs.version.outputs.version}}

      - name: Build
        run: cmake --build build

      - name: Check binary
        run: test -f build/nosh

      - uses: actions/upload-artifact@v4
        with:
          name: nosh-macos
          path: |
            build/nosh*
            build/*.dylib

  build-windows:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-mingw-w64 g++-mingw-w64 make mingw-w64-tools

      - name: Configure CMake
        run: |
          cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=cmake/windows-toolchain.cmake \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DVERSION=${{needs.version.outputs.version}}

      - name: Build
        run: cmake --build build

      - name: Check binary
        run: test -f build/nosh.exe

      - uses: actions/upload-artifact@v4
        with:
          name: nosh-windows
          path: |
            build/nosh*
            build/*.dll