name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: get_version
        name: Get version
        run: |
          VERSION="0.1.0"
          COMMIT=$(git rev-parse --short HEAD || echo "unknown")
          VERSION_STRING="$VERSION-$COMMIT"
          echo "version=$VERSION_STRING" >> $GITHUB_OUTPUT

  build-linux:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config \
            libreadline-dev libmbedtls-dev libargon2-dev
      - name: Configure CMake
        run: cmake -B build -DVERSION=${{needs.version.outputs.version}}
      - name: Build
        run: cmake --build build
      - name: Test binary
        run: |
          test -f build/nosh
          ./build/nosh --version || true
      - uses: actions/upload-artifact@v4
        with:
          name: nosh-linux
          path: build/nosh*

  build-macos:
    needs: version
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install cmake readline openssl argon2 mbedtls
      - name: Install x86_64 dependencies
        if: matrix.arch == 'x86_64'
        run: |
          arch -x86_64 brew install mbedtls argon2
      - name: Configure CMake
        run: |
          cmake -B build-${{ matrix.arch }} \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DOPENSSL_ROOT_DIR=$(brew --prefix openssl) \
            -DCMAKE_BUILD_TYPE=Release \
            "-DCMAKE_C_FLAGS=-DNOSH_VERSION=\"${{needs.version.outputs.version}}\"" \
            -DVERSION=${{needs.version.outputs.version}}
      - name: Build
        run: cmake --build build-${{ matrix.arch }}
      - name: Test binary (skip for arm64 on Intel runners)
        if: matrix.arch == 'x86_64'
        run: |
          test -f build-${{ matrix.arch }}/nosh
          ./build-${{ matrix.arch }}/nosh --version || true
      - name: Upload x86_64 artifact for universal binary
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: nosh-macos-x86_64
          path: build-x86_64/nosh
          retention-days: 1
      - name: Download x86_64 build
        if: matrix.arch == 'arm64'
        uses: actions/download-artifact@v4
        with:
          name: nosh-macos-x86_64
          path: build-x86_64
      - name: Create Universal Binary
        if: matrix.arch == 'arm64'
        run: |
          chmod +x build-x86_64/nosh
          mkdir -p build
          lipo -create -output build/nosh \
            build-x86_64/nosh \
            build-arm64/nosh
      - uses: actions/upload-artifact@v4
        if: matrix.arch == 'arm64'
        with:
          name: nosh-macos-universal
          path: build/nosh

  build-windows:
    needs: version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        shell: pwsh
        run: |
          vcpkg install readline:x64-windows mbedtls:x64-windows argon2:x64-windows `
            dirent:x64-windows getopt:x64-windows
      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B build -S . `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DCMAKE_C_FLAGS="/D_CRT_SECURE_NO_WARNINGS /DWIN32_LEAN_AND_MEAN /DWINVER=0x0601 /D_WIN32_WINNT=0x0601" `
            -DCMAKE_BUILD_TYPE=Release `
            -DVERSION=${{needs.version.outputs.version}}
      - name: Build
        run: cmake --build build --config Release
      - name: Test binary
        shell: pwsh
        run: |
          if (!(Test-Path "build/Release/nosh.exe")) { exit 1 }
          .\build\Release\nosh.exe --version
      - uses: actions/upload-artifact@v4
        with:
          name: nosh-windows
          path: |
            build/Release/nosh.exe
            build/Release/*.dll