name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libreadline-dev libsodium-dev

      - name: Build
        run: make

      - name: Check binary exists
        run: test -f nosh

      - name: Test version command
        run: |
          ./nosh --version || true

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure Homebrew is installed
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";
          fi

      - name: Install dependencies
        run: |
          brew install gcc readline libsodium

      - name: Set Sodium environment variables
        run: |
          echo 'LDFLAGS="-L/usr/local/opt/libsodium/lib"' >> $GITHUB_ENV
          echo 'CPPFLAGS="-I/usr/local/opt/libsodium/include"' >> $GITHUB_ENV
          echo 'PKG_CONFIG_PATH="/usr/local/opt/libsodium/lib/pkgconfig"' >> $GITHUB_ENV

      - name: Build
        run: make
        env:
          LDFLAGS: "-L/usr/local/opt/libsodium/lib"
          CPPFLAGS: "-I/usr/local/opt/libsodium/include"
          PKG_CONFIG_PATH: "/usr/local/opt/libsodium/lib/pkgconfig"

      - name: Check binary exists
        run: test -f nosh

      - name: Test version command
        run: |
          ./nosh --version || true

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure Chocolatey is installed
        run: |
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force;
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
          }

      - name: Install dependencies
        run: |
          choco install -y mingw make libsodium

      - name: Set Sodium environment variables
        run: |
          $env:Path += ";C:\Program Files\libsodium\bin"
          $env:INCLUDE = "C:\Program Files\libsodium\include"
          $env:LIB = "C:\Program Files\libsodium\lib"

      - name: Build
        run: |
          make

      - name: Check binary exists
        run: if exist nosh.exe (echo Binary exists) else (exit 1)

      - name: Test version command
        run: |
          .\nosh.exe --version || true